// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = ackv1alpha1.AWSAccountID("")
)

// Details about an OpenSearch Serverless access policy.
type AccessPolicyDetail struct {
	CreatedDate      *int64  `json:"createdDate,omitempty"`
	Description      *string `json:"description,omitempty"`
	LastModifiedDate *int64  `json:"lastModifiedDate,omitempty"`
	Name             *string `json:"name,omitempty"`
	PolicyVersion    *string `json:"policyVersion,omitempty"`
}

// Statistics for an OpenSearch Serverless access policy.
type AccessPolicyStats struct {
	DataPolicyCount *int64 `json:"dataPolicyCount,omitempty"`
}

// A summary of the data access policy.
type AccessPolicySummary struct {
	CreatedDate      *int64  `json:"createdDate,omitempty"`
	Description      *string `json:"description,omitempty"`
	LastModifiedDate *int64  `json:"lastModifiedDate,omitempty"`
	Name             *string `json:"name,omitempty"`
	PolicyVersion    *string `json:"policyVersion,omitempty"`
}

// Details about each OpenSearch Serverless collection, including the collection
// endpoint and the OpenSearch Dashboards endpoint.
type CollectionDetail struct {
	ARN                *string `json:"arn,omitempty"`
	CollectionEndpoint *string `json:"collectionEndpoint,omitempty"`
	CreatedDate        *int64  `json:"createdDate,omitempty"`
	DashboardEndpoint  *string `json:"dashboardEndpoint,omitempty"`
	Description        *string `json:"description,omitempty"`
	FailureCode        *string `json:"failureCode,omitempty"`
	FailureMessage     *string `json:"failureMessage,omitempty"`
	ID                 *string `json:"id,omitempty"`
	KMSKeyARN          *string `json:"kmsKeyARN,omitempty"`
	LastModifiedDate   *int64  `json:"lastModifiedDate,omitempty"`
	Name               *string `json:"name,omitempty"`
	StandbyReplicas    *string `json:"standbyReplicas,omitempty"`
	Status             *string `json:"status,omitempty"`
	Type               *string `json:"type_,omitempty"`
}

// Error information for an OpenSearch Serverless request.
type CollectionErrorDetail struct {
	ErrorCode    *string `json:"errorCode,omitempty"`
	ErrorMessage *string `json:"errorMessage,omitempty"`
	ID           *string `json:"id,omitempty"`
	Name         *string `json:"name,omitempty"`
}

// A list of filter keys that you can use for LIST, UPDATE, and DELETE requests
// to OpenSearch Serverless collections.
type CollectionFilters struct {
	Name   *string `json:"name,omitempty"`
	Status *string `json:"status,omitempty"`
}

// Details about each OpenSearch Serverless collection.
type CollectionSummary struct {
	ARN    *string `json:"arn,omitempty"`
	ID     *string `json:"id,omitempty"`
	Name   *string `json:"name,omitempty"`
	Status *string `json:"status,omitempty"`
}

// Details about the created OpenSearch Serverless collection.
type CreateCollectionDetail struct {
	ARN              *string `json:"arn,omitempty"`
	CreatedDate      *int64  `json:"createdDate,omitempty"`
	Description      *string `json:"description,omitempty"`
	ID               *string `json:"id,omitempty"`
	KMSKeyARN        *string `json:"kmsKeyARN,omitempty"`
	LastModifiedDate *int64  `json:"lastModifiedDate,omitempty"`
	Name             *string `json:"name,omitempty"`
	StandbyReplicas  *string `json:"standbyReplicas,omitempty"`
	Status           *string `json:"status,omitempty"`
	Type             *string `json:"type_,omitempty"`
}

// Details about a deleted OpenSearch Serverless collection.
type DeleteCollectionDetail struct {
	ID     *string `json:"id,omitempty"`
	Name   *string `json:"name,omitempty"`
	Status *string `json:"status,omitempty"`
}

// Error information for an OpenSearch Serverless request.
type EffectiveLifecyclePolicyDetail struct {
	PolicyName      *string `json:"policyName,omitempty"`
	Resource        *string `json:"resource,omitempty"`
	RetentionPeriod *string `json:"retentionPeriod,omitempty"`
}

// Error information for an OpenSearch Serverless request.
type EffectiveLifecyclePolicyErrorDetail struct {
	ErrorCode    *string `json:"errorCode,omitempty"`
	ErrorMessage *string `json:"errorMessage,omitempty"`
	Resource     *string `json:"resource,omitempty"`
}

// Describes IAM Identity Center options for an OpenSearch Serverless security
// configuration in the form of a key-value map.
type IAMIdentityCenterConfigOptions struct {
	ApplicationDescription *string `json:"applicationDescription,omitempty"`
	ApplicationName        *string `json:"applicationName,omitempty"`
}

// Details about an OpenSearch Serverless lifecycle policy.
type LifecyclePolicyDetail struct {
	CreatedDate      *int64  `json:"createdDate,omitempty"`
	Description      *string `json:"description,omitempty"`
	LastModifiedDate *int64  `json:"lastModifiedDate,omitempty"`
	Name             *string `json:"name,omitempty"`
	PolicyVersion    *string `json:"policyVersion,omitempty"`
}

// Error information for an OpenSearch Serverless request.
type LifecyclePolicyErrorDetail struct {
	ErrorCode    *string `json:"errorCode,omitempty"`
	ErrorMessage *string `json:"errorMessage,omitempty"`
	Name         *string `json:"name,omitempty"`
}

// The unique identifiers of policy types and policy names.
type LifecyclePolicyIdentifier struct {
	Name *string `json:"name,omitempty"`
}

// Statistics for an OpenSearch Serverless lifecycle policy.
type LifecyclePolicyStats struct {
	RetentionPolicyCount *int64 `json:"retentionPolicyCount,omitempty"`
}

// A summary of the lifecycle policy.
type LifecyclePolicySummary struct {
	CreatedDate      *int64  `json:"createdDate,omitempty"`
	Description      *string `json:"description,omitempty"`
	LastModifiedDate *int64  `json:"lastModifiedDate,omitempty"`
	Name             *string `json:"name,omitempty"`
	PolicyVersion    *string `json:"policyVersion,omitempty"`
}

// Describes SAML options for an OpenSearch Serverless security configuration
// in the form of a key-value map.
type SamlConfigOptions struct {
	SessionTimeout *int64 `json:"sessionTimeout,omitempty"`
}

// Details about a security configuration for OpenSearch Serverless.
type SecurityConfigDetail struct {
	ConfigVersion    *string `json:"configVersion,omitempty"`
	CreatedDate      *int64  `json:"createdDate,omitempty"`
	LastModifiedDate *int64  `json:"lastModifiedDate,omitempty"`
}

// Statistics for an OpenSearch Serverless security configuration.
type SecurityConfigStats struct {
	SamlConfigCount *int64 `json:"samlConfigCount,omitempty"`
}

// A summary of a security configuration for OpenSearch Serverless.
type SecurityConfigSummary struct {
	ConfigVersion    *string `json:"configVersion,omitempty"`
	CreatedDate      *int64  `json:"createdDate,omitempty"`
	LastModifiedDate *int64  `json:"lastModifiedDate,omitempty"`
}

// Details about an OpenSearch Serverless security policy.
type SecurityPolicyDetail struct {
	CreatedDate      *int64  `json:"createdDate,omitempty"`
	Description      *string `json:"description,omitempty"`
	LastModifiedDate *int64  `json:"lastModifiedDate,omitempty"`
	Name             *string `json:"name,omitempty"`
	PolicyVersion    *string `json:"policyVersion,omitempty"`
	Type             *string `json:"type_,omitempty"`
}

// Statistics for an OpenSearch Serverless security policy.
type SecurityPolicyStats struct {
	EncryptionPolicyCount *int64 `json:"encryptionPolicyCount,omitempty"`
	NetworkPolicyCount    *int64 `json:"networkPolicyCount,omitempty"`
}

// A summary of a security policy for OpenSearch Serverless.
type SecurityPolicySummary struct {
	CreatedDate      *int64  `json:"createdDate,omitempty"`
	Description      *string `json:"description,omitempty"`
	LastModifiedDate *int64  `json:"lastModifiedDate,omitempty"`
	Name             *string `json:"name,omitempty"`
	PolicyVersion    *string `json:"policyVersion,omitempty"`
	Type             *string `json:"type_,omitempty"`
}

// A map of key-value pairs associated to an OpenSearch Serverless resource.
type Tag struct {
	Key   *string `json:"key,omitempty"`
	Value *string `json:"value,omitempty"`
}

// Details about an updated OpenSearch Serverless collection.
type UpdateCollectionDetail struct {
	ARN              *string `json:"arn,omitempty"`
	CreatedDate      *int64  `json:"createdDate,omitempty"`
	Description      *string `json:"description,omitempty"`
	ID               *string `json:"id,omitempty"`
	LastModifiedDate *int64  `json:"lastModifiedDate,omitempty"`
	Name             *string `json:"name,omitempty"`
	Status           *string `json:"status,omitempty"`
	Type             *string `json:"type_,omitempty"`
}

// Update details for an OpenSearch Serverless-managed interface endpoint.
type UpdateVPCEndpointDetail struct {
	LastModifiedDate *int64 `json:"lastModifiedDate,omitempty"`
}

// Details about an OpenSearch Serverless-managed interface endpoint.
type VPCEndpointDetail struct {
	CreatedDate    *int64  `json:"createdDate,omitempty"`
	FailureCode    *string `json:"failureCode,omitempty"`
	FailureMessage *string `json:"failureMessage,omitempty"`
}

// Error information for a failed BatchGetVpcEndpoint request.
type VPCEndpointErrorDetail struct {
	ErrorCode    *string `json:"errorCode,omitempty"`
	ErrorMessage *string `json:"errorMessage,omitempty"`
}
